<?php
declare(strict_types=1);

namespace MyOnlineStore\Omnipay\MultiSafepay\Message;

use Omnipay\Common\Message\AbstractResponse;

/**
 * MultiSafepay Rest Api Abstract Response class.
 *
 * All Response classes within the Rest namespace
 * inheritance from this class.
 */
abstract class Response extends AbstractResponse
{
    /**
     * Is the response successful?
     */
    public function isSuccessful(): bool
    {
        if (!isset($this->data['success'])) {
            return false;
        }

        return $this->data['success'];
    }

    /**
     * Response Message.
     *
     * @return string|null A response message from the payment gateway
     */
    public function getMessage(): ?string
    {
        if (isset($this->data['error_info']) && !$this->isSuccessful()) {
            return $this->data['error_info'];
        }

        return null;
    }

    /**
     * Response code.
     *
     * @return string|null A response code from the payment gateway
     */
    public function getCode(): ?string
    {
        if (isset($this->data['error_code']) && !$this->isSuccessful()) {
            return (string) $this->data['error_code'];
        }

        return null;
    }

    /**
     * Gateway Reference.
     *
     * @return string|null A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference(): ?string
    {
        if (isset($this->data['data']['transaction_id'])) {
            return (string) $this->data['data']['transaction_id'];
        }

        return null;
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @psalm-suppress InvalidNullableReturnType
     */
    public function getTransactionId(): ?string
    {
        if (isset($this->data['data']['order_id'])) {
            return (string) $this->data['data']['order_id'];
        }

        /** @psalm-suppress NullableReturnStatement */
        return null;
    }
}
