name: Test

on: push

jobs:
    test:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: ['ubuntu-18.04', 'ubuntu-20.04']
                php-version: ['7.2', '7.3', '7.4']

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: xdebug

            -   name: Get composer cache directory
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache Dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    key: composer-${{ matrix.operating-system }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        composer-${{ matrix.operating-system }}-${{ matrix.php-version }}-
                        composer-${{ matrix.operating-system }}-
                        composer-

            -   name: Install Dependencies
                run: composer install --no-ansi --no-interaction --no-progress --no-suggest

            -   name: Code Sniffer
                run: vendor/bin/phpcs

            -   name: Setup problem matchers for PHPUnit
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: PHPUnit
                run: vendor/bin/phpunit

            -   name: Psalm
                run: vendor/bin/psalm --output-format=github
